language: r
cache: packages

matrix:
  include:
    - os: linux
      r: 3.2
    - os: linux
      r: oldrel
    - os: linux
      r: release
      after_success:
        R -e 'covr::codecov()'
      before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
      deploy:
        provider: script
        script: Rscript -e 'pkgdown::deploy_site_github()'
        skip_cleanup: true
    - os: linux
      r: devel
    - os: linux
      env: R_CODECOV=true
    - os: osx
      osx_image: xcode8.3
    - os: osx
      osx_image: xcode8.3
      before_install:
        - brew install libxml2
        - brew link --force libxml2

addons:
  apt:
    packages:
      - libxml2-dev

warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: change
